### ISSUE TITLE
It doesn't work for me. 

### ISSUE THREAD

**Issue by peace20021** [danegottwald/BetterDiscordPlugins#6]
Hi, For some reason I have my plugins turned on, but it doesn't work for me. Can you check if it's still work? I'm using
Stable 106905 (1eb8c0f)
BetterDiscord 1.3.0
Host 1.0.9003 
Windows 10 64-Bit (10.0.19043)

**Comment by 50l3r** [comment]
+1 :P

**Comment by killerfrienddk** [comment]
This Issue happens on when you are activating the plugin, it will then overwrite the old file and not add the new file with the zero library @peace20021 @50l3r

**Comment by NightPlay** [comment]
also doesnt work for me, i didnt understand above comment still need help

**Comment by killerfrienddk** [comment]
You will have to rename the plugin you installed to "0PluginLibrary.plugin.js" because it overwrites, the "HideStreamPreview.plugin.js" with the "0PluginLibrary.plugin.js"'s content, then put the "HideStreamPreview.plugin.js" in the the plugins folder again and you are golden. @NightPlay 
I have made a pull request where this is fixed how ever it would seem that @danegottwald has not had time to implement it yet.

**Comment by danegottwald** [comment]
Sorry, been busy with school and just checked on my personal GitHub.  Mine has been working with no problems, may be because of some [ZeresPluginLibrary](https://betterdiscord.app/plugin/ZeresPluginLibrary) updates.  I went ahead and merged @killerfrienddk 's pull request.  Should be fixed if that was indeed the reason for error.

Pinging each to notify of the fix and to try the new update: @NightPlay  @50l3r  @peace20021
